### ISSUE TITLE
Upload fails with old version of aws-sdk.

### ISSUE THREAD

**Issue by charlescbeebe** [jamestalmage/s3-static-site-uploader#2]
A freshly-installed s3-upload fails for me like so:

```
>> s3-upload: /Users/charles/.nvm/versions/node/v0.12.0/lib/node_modules/s3-upload/node_modules/aws-sdk/lib/sequential_executor.js:261
>>         throw err;
>>               ^
>> TypeError: Cannot read property 'length' of null
>>     at Object.AWS.util.buffer.concat (/Users/charles/.nvm/versions/node/v0.12.0/lib/node_modules/s3-upload/node_modules/aws-sdk/lib/util.js:116:29)
>>     at Request.HTTP_DONE (/Users/charles/.nvm/versions/node/v0.12.0/lib/node_modules/s3-upload/node_modules/aws-sdk/lib/event_listeners.js:214:36)
>>     at Request.callListeners (/Users/charles/.nvm/versions/node/v0.12.0/lib/node_modules/s3-upload/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
>>     at Request.emit (/Users/charles/.nvm/versions/node/v0.12.0/lib/node_modules/s3-upload/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
>>     at Request.emitEvent (/Users/charles/.nvm/versions/node/v0.12.0/lib/node_modules/s3-upload/node_modules/aws-sdk/lib/request.js:408:10)
>>     at IncomingMessage.onEnd (/Users/charles/.nvm/versions/node/v0.12.0/lib/node_modules/s3-upload/node_modules/aws-sdk/lib/event_listeners.js:184:26)
>>     at IncomingMessage.emit (events.js:129:20)
>>     at _stream_readable.js:908:16
>>     at process._tickCallback (node.js:355:11)
```

Updating to aws-sdk@2 fixes whatever it was that was causing this issue. Please bump the version of aws-sdk in the package.json :)

**Comment by jamestalmage** [comment]
published to npm as `0.0.2`
